services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=userName
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
